# Generated by Django 4.2.7 on 2023-11-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_target_model_delete_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target_model',
            name='target_id',
            field=models.CharField(max_length=200),
        ),
    ]
