# Generated by Django 4.2.7 on 2023-11-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_target_model_new_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='target_model',
            name='new_field2',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
