# Generated by Django 4.2.7 on 2023-11-27 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowless', '0002_pressure_sensor_installation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressure_Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='pressure_sensor',
            name='installation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 17, 8, 21, 478900), verbose_name='date created'),
        ),
    ]
