# Generated by Django 4.2.7 on 2023-11-27 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowless', '0003_pressure_reading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressure_sensor',
            name='installation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 17, 19, 16, 143249), verbose_name='installation date'),
        ),
    ]
