# Generated by Django 4.2.7 on 2023-11-27 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowless', '0004_alter_pressure_sensor_installation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressure_reading',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 17, 49, 53, 269612), verbose_name='installation date'),
        ),
        migrations.AddField(
            model_name='pressure_reading',
            name='sensor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='flowless.pressure_sensor', verbose_name='Sensor'),
        ),
        migrations.AddField(
            model_name='pressure_reading',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pressure_sensor',
            name='installation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 17, 49, 53, 269612), verbose_name='installation date'),
        ),
    ]
